[package]
name = "rust-processor"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
byteorder = "1.4"
ctrlc = "3.2"
libc = "0.2"
ring = "0.16"

[[bin]]
name = "rust-processor"
path = "main.rs"